### ISSUE TITLE
Link to Android 2.0  documentation goes to 404

### ISSUE THREAD

**Issue by itunlimited** [Adobe-Marketing-Cloud/video-heartbeat-v2#1]
when trying to access the following link on Code>Releases and in the README.md file, the link goes to a 404 page.
https://marketing.adobe.com/resources/help/sc/appmeasurement/hbvideo/android_2.0/

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: resources/help/sc/appmeasurement/hbvideo/android_2.0/index.html
RequestId: E7798F47C754DC19
HostId: 7xS45Jjktx/8rwk+kzWHPkCqqa7JdeoAYEkm4At9KttPYnTHxzW05OP0xwkc+0c2maCKq3LMkl0=

**Comment by alcazes** [comment]
correct link is https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/android_2.0/

**Comment by diux** [comment]
Fixed in latest release
