### ISSUE TITLE
Multiple Start Events during Ad Play

### ISSUE THREAD

**Issue by rgr-myrg** [Adobe-Marketing-Cloud/video-heartbeat-v2#10]
Adobe Team:

I'm seeing multiple start events firing during playback when an Ad Break contains multiple Ad items.

s:event:type | s:asset:type | duration
-------------|-------------|-------------
start | ad | 0
aa_ad_start | ad | 0
start | ad | 624
play | ad | 10080

Notice there are two _start_ events in the above sequence.

I've ensured on my end the player is propagating the correct events into Video HB. Also, during testing, I've seen Video HB SDK is robust enough not to allow duplicate or out of sequence events from firing. For example if trackPlay() is invoked out of sequence, the following message is generated:

```javascript
AdobeHeartbeatAgent _trackHeartbeatInfo action = ["Play"]
VideoHeartbeat-2.0.2.min.js:28 [11:59:47 GMT-0500 (EST).257] [ERROR] [MediaHeartbeat] API call trackPlay is unsupported in the current state.
```
This leads me to conclude that multiple _start_ events are being generated from your SDK.

Is there a known condition or sequence of events that may cause this anomaly? 

I've captured a Charles session and can provide one if requested.

Many thanks for looking into this.

**Comment by praveek** [comment]
Hi @rgr-myrg 

Seeing multiple main:start or ad:start events is expected. The accumulated duration of the start calls get reported as Video/Ad Time to Start metric in the dashboard. 

Thanks.
