### ISSUE TITLE
Multiple ad starts during midroll ad play

### ISSUE THREAD

**Issue by awongwork** [Adobe-Marketing-Cloud/video-heartbeat-v2#13]
We've noticed that during midroll ad play, somehow multiple start events are generated between a single set of ad start and ad complete events.  As show in the console log, we were only calling `trackAdStart()` and `trackAdComplete()` per ad:  

![image](https://user-images.githubusercontent.com/4719921/36814961-314a9db6-1ca7-11e8-9ae5-5de75919df2a.png)

However, between each ad start / ad complete pair, instead of getting play events for the ad, we were getting starts:  

![image](https://user-images.githubusercontent.com/4719921/36815043-78d49f38-1ca7-11e8-98c8-c49f2295ba5f.png)

If we were to explicitly call `trackPlay()` after calling `trackAdStart()`, then the issue is resolved, however, we end up with unexpected content play events being fired in between ads. 

Can you advice is that is the expected order of the function calls?  Are we expected to call `trackPlay()` per ad play?  Or is this a bug?

**Comment by himanshuphalak** [comment]
Hi @awongwork, just before the AdStart API call I do see a call for trackPause, is that intended? To get play events during an Ad, VHL SDK needs to be in playing state for which trackPlay API has to be called. Or if you can just avoid that trackPause (unless player is really in paused state) before AdStart that should fix the problem for you. 

Also, about getting content play events in between Ads is caused if the gap between two different Ads is more than 250ms. For more information about this and workaround please follow this documentation: https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/cookbook/c_vhl_cookbook_fix-ad-mainstart-ad.html

**Comment by awongwork** [comment]
@himanshuphalak Thank you for your response!  No, we didn't call `trackPause()` explicitly, I suspect it was generated by `trackAdStart()` based on `HB 1.x` documentation:

![image](https://user-images.githubusercontent.com/4719921/36856726-ad7bbc7e-1d44-11e8-98d8-40d75dbb5dd8.png)

Not sure if that's the  case for 2.x
https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/vhl-dev-guide-v15_js.pdf

I managed to solve the issue by calling `trackPlay()` after every ad start, which seems to yield the correct behaviour.

**Comment by himanshuphalak** [comment]
@awongwork The documentation you are referring to is outdated and only applies to 1.5 SDK version. If you could share the logs un-filtered for this given scenario, we can look into what is causing that trackPause. Alternatively, it would be great if you can provide a link to your application that we could look at.

**Comment by awongwork** [comment]
@himanshuphalak Is there somewhere where I can share the link privately?

**Comment by himanshuphalak** [comment]
@awongwork Best way to go forward would be to file a ticket with [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html).

**Comment by awongwork** [comment]
Thank you!
