### ISSUE TITLE
Roku - Track Buffering - updateRefTSForEvent()

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/video-heartbeat-v2#14]
When we track "trackBufferComplete", it calls the below function - 

   <code>_adb_mediacontext().updateRefTSForEvent("buffer", "-1")</code>

But I dont see the implementation of function `updateRefTSForEvent` in `_adb_mediacontext()`.
This is throwing an error in the Roku Debugger.

**Comment by himanshuphalak** [comment]
@dipan-majumder Thanks for reporting the issue. We have included the fix in our latest release v2.0.4

**Comment by himanshuphalak** [comment]
@dipan-majumder Please let us know if the latest SDK version resolved the issue for you.

**Comment by dipan-majumder** [comment]
Sure, I will check and let you know, thanks for the update.

**Comment by dipan-majumder** [comment]
@himanshuphalak Yes, its working fine in v2.0.4 thanks!
