### ISSUE TITLE
adTrackingInterval configuration

### ISSUE THREAD

**Issue by awongwork** [Adobe-Marketing-Cloud/video-heartbeat-v2#15]
When the video enters an ad break, the tracking interval becomes 1 second rather than 10 seconds.  Is that expected behaviour?  Is it possible for the API to expose the adTrackingInterval configuration in case the 1 second interval poses performance issues?

**Comment by himanshuphalak** [comment]
@awongwork Yes, 1 second Ad tracking is one of the features for SDK v2.1. We have standardized our ad tracking solution to 1 second and hence there is no API to configure it.

**Comment by awongwork** [comment]
Thank you for clarifying @himanshuphalak
