### ISSUE TITLE
Initializing AdobeHeartbeat

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/video-heartbeat-v2#16]
Hi,

I just want to check if Heartbeat initialization values can be passed as a parameter from the app rather then adobe referring directly to the `Adobemobileconfig.json` file. We want to keep this json file in an external server and make it easily configurable. Can we do it without changing the `adbmobile.brs` code from our side? Thanks, Dipan.

**Comment by himanshuphalak** [comment]
@dipan-majumder Currently we do not allow remote loading of AdobeMobileConfig.json and it needs to be packaged with the application.

**Comment by dipan-majumder** [comment]
@himanshuphalak Ok, probably I can try changing the `adbmobile.brs` file to load external values.
