### ISSUE TITLE
Heartbeat does not play well inside self-enclosed function

### ISSUE THREAD

**Issue by adurgavich** [Adobe-Marketing-Cloud/video-heartbeat-v2#2]
If you have Heartbeat base code (VideoHeartbeat.min.js) inside of a self-enclosed function, you do not have access to some variables that are needed for the Heartbeat bridge to work since they are not scoped to `window`.

Some objects that should be scoped to `window` are `ADB` and `Heartbeat`

**Comment by praveek** [comment]
@adurgavich Enclosing Heartbeat base code inside of a self-enclosed function will by default export everything to window.ADB unless the function is bound to a different object. By Heartbeat bridge do you refer the tracking implementation in the sample application ?
