### ISSUE TITLE
JS SDK: trackSessionStart, heartbeat firing start events

### ISSUE THREAD

**Issue by stefanovualto** [Adobe-Marketing-Cloud/video-heartbeat-v2#20]
in the sdk Version 2.1.0. Is it a normal behavior that if we call "trackSessionStart" on the "videoLoad" event the sdk fires "start" events every ~2seconds?

**Comment by praveek** [comment]
@stefanovualto Yes. It is normal behaviour to see multiple ```start``` events till the video has first started playing. We compute the "timeToStart" metric based on the total event durations of all the start events. The SDK sends multiple ```main:start``` events or in case of a preroll ad multiple ```ad:start``` events until the first call to ```trackPlay```.

**Comment by praveek** [comment]
The following API calls are allowed after TrackSessionStart

- TrackPlay
- TrackPause
- TrackEvent(SeekStart)
- TrackEvent(BufferStart)
- TrackEvent(AdBreakStart) 
- TrackEvent(ChapterStart)
- TrackError

The SDK prints a warning and ignores other invalid API calls.
