### ISSUE TITLE
Roku change request: initialise config with external config

### ISSUE THREAD

**Issue by davidrooks** [Adobe-Marketing-Cloud/video-heartbeat-v2#21]
Currently, adb_mobile config is expected to be packaged with the app in "pkg:/ADBMobileConfig.json"

This creates a problem here at Sky as we have different config requirements for each country but we still want a single app that works everywhere.

To resolve this issue we have updated the adobe libraray to allow us to specifiy at runtime the ADBMobileConfig. We would like this change to be integrated into the official library. 

If this makes sense then i am happy to submit a PR with proposed changes

**Comment by timbeynart-nbcuni** [comment]
Second that request for NBCUniversal.

**Comment by praveek** [comment]
We are planning to address this with our next release.

Thanks.

**Comment by himanshuphalak** [comment]
Closing this ticket as we will be including this into our next Roku release.
