### ISSUE TITLE
Type mismatch in timer stop

### ISSUE THREAD

**Issue by craigster1991** [Adobe-Marketing-Cloud/video-heartbeat-v2#24]
This is occurring on both Roku and NowTV.
I'm using the latest version of the library.

When the timer stop method is called, the logger attempts to concatenate an invalid variable (m._name) into a string.

This would appear the start method isn't setting m._name?

`Current Function:`
`5207:  Function() As Void`
`5208:          if m._enabled = true`
`5209:            _adb_logger().debug("Timer - stoping " + m._name + " timer.")`
`5210:            m._enabled = false`
`5211:            m._nextTick = invalid`
`5212:          else`
`5213:*           _adb_logger().debug("Timer -  " + m._name + " timer already stopped.")`
`5214:          endif`
`5215:        End Function,`
`Type Mismatch. (runtime error &h18) in pkg:/source/adbmobile.brs(5213)`
`5213:           _adb_logger().debug("Timer -  " + m._name + " timer already stopped.")`

**Comment by craigster1991** [comment]
This is not really an issue client care can help with. It's more a code issue that the stop method is sometimes called when the `m._name` variable is unset.
I've created a PR here: https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/pull/26

**Comment by praveek** [comment]
@craigster1991 Thanks for the PR. We have already fixed this issue internally for version 2.1 which will be releasing in the first week of August.

Thanks,
Praveen

**Comment by praveek** [comment]
@craigster1991  This has been fixed in 2.1 version of our roku library (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/roku-v2.1.0).

**Comment by craigster1991** [comment]
Closing due to above.
