### ISSUE TITLE
Roku: ad position in an adBreak

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/video-heartbeat-v2#27]
Hi,

I believe the parameter `position` in the function `adb_media_init_adinfo(name As String, id As String, position As Double, length As Double)` refers to the ad unit position within that ad_pod. 
But even after incrementing it properly for every ad, it is not reflecting in the proxy debugger.
In the proxy debugger (we use Charles), `s:asset:pod_position` is not incrementing for each ad within the ad pod. Rather it looks like the Ad Pod Index. 
But we thought `position` in the above function is actually the `s:asset:pod_position`. Please suggest. Thanks!

**Comment by dipan-majumder** [comment]
Hi @praveek / @himanshuphalak ,
Let me know if you have any update on my last comment. 
Thanks!

**Comment by himanshuphalak** [comment]
Hi @dipan-majumder, you are correct, `a:asset:pod_position` on Heartbeat call and `a.media.ad.podPosition` on Analytics call refers to `AdInfo.position`. There was a bug in our SDK where `a.media.ad.podPosition` was correctly populated but `a:asset:pod_position` was not. We have fixed it in v2.1 and will soon be released.

**Comment by praveek** [comment]
@dipan-majumder This has been fixed in 2.1 version of our roku library (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/roku-v2.1.0).

**Comment by dipan-majumder** [comment]
This is fixed, thanks!
