### ISSUE TITLE
Space before some of the numeric values

### ISSUE THREAD

**Issue by dipan-majumder** [Adobe-Marketing-Cloud/video-heartbeat-v2#28]
Hi, 

In the pings going out of the device, some of the param values have spaces before the numeric values even though we pass only integer values to the heartbeat sdk through the params. We want to get rid these spaces, can you please advice.

Here is one url for example:

You can see some of params in the below url have spaces before the values (for example: startup_time, chapter_offset, chapter_length, length, bitrate, chapter_pos). 
And we also see this for ad_length etc (not in the below url).

http://nbcume.hb.omtrdc.net/?h%3Asc%3Assl=0&l%3Astream%3Astartup_time=%200&s%3Aevent%3Atype=play&l%3Astream%3Achapter_offset=%200&s%3Asp%3Aplayer_name=Roku%20Player&l%3Aevent%3Ats=1532623931327&s%3Asp%3Ahb_version=roku-2.0.4.50-9f49b4&l%3Asp%3Ahb_api_lvl=4&s%3Aevent%3Asid=1532623854613877847088&s%3Asp%3Achannel=On-Domain&s%3Aasset%3Apublisher=A8AB776A5245B4220A490D44%40AdobeOrg&s%3Astream%3Achapter_sid=1532623931325297877290&l%3Aevent%3Aduration=1&l%3Aaam%3Aloc_hint=7&s%3Astream%3Achapter_name=chapter&s%3Aasset%3Aname=AmyBoy&l%3Astream%3Afps=%200&s%3Asc%3Arsid=nbcutvemobileapp&s%3Astream%3Achapter_id=cfb12c34419b9f1b8f760ffd01384f1f_1&s%3Asp%3Asdk=CPC-ROKU&l%3Astream%3Abitrate=%20867000&s%3Asc%3Atracking_server=nbcume.sc.omtrdc.net&s%3Aaam%3Ablob=6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y&l%3Aevent%3Aplayhead=0&s%3Asp%3Aovp=Roku&l%3Astream%3Achapter_pos=%201&s%3Aasset%3Avideo_id=3765575&l%3Astream%3Achapter_length=%20857&s%3Astream%3Atype=VOD%20Episode&l%3Aasset%3Alength=%202456&l%3Aevent%3Aprev_ts=1532623871337&s%3Auser%3Amid=24164833107306564443144207284189536918&l%3Astream%3Adropped_frames=%200&s%3Aasset%3Atype=main

Thanks!

**Comment by praveek** [comment]
@dipan-majumder Some of the values have extra space in front of them as "Str" function in BrightScript adds a leading space when serializing positive numbers. This will not affect reporting/tracking as our analytics backend handles it correctly. 

We have fixed this behaviour to not include extra spaces in v2.1 of our SDK.

Thanks,
Praveen

**Comment by dipan-majumder** [comment]
@praveek ok, and v2.1 is scheduled to be be released in Aug 1st week?

**Comment by himanshuphalak** [comment]
@dipan-majumder, we will keep you posted as soon as release is available.

**Comment by praveek** [comment]
@dipan-majumder This has been fixed in 2.1 version of our roku library (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/roku-v2.1.0).

**Comment by dipan-majumder** [comment]
This is fixed, thanks!
