### ISSUE TITLE
IOS sdk: scientific notation for content length 

### ISSUE THREAD

**Issue by Gregoirevda** [Adobe-Marketing-Cloud/video-heartbeat-v2#29]
The `Media Stream Start` event prints `1.08e+07` for `a.media.length`
but `main:start` event prints `10800000` for `l:asset:length`
resulting in an error in the `main:start` event:
`[VHL-SC Video Info] Expected: 1.08e+07 (Adobe Analytics[a.media.length]).`

Could it be that the string parsing in IOS isn't the same for both events?
I only have one implementation:

```objective-c
- (double) getTrackSessionLength: (NSDate*) startTime endTime: (NSDate*) endTime {
  NSTimeInterval seconds = [endTime timeIntervalSinceDate:startTime];
  return seconds * 1000;
};
```

**Comment by himanshuphalak** [comment]
Hi @Gregoirevda can you clarify what component throws that error? "`[VHL-SC Video Info] Expected: 1.08e+07 (Adobe Analytics[a.media.length]).`" doesn't look like something VHL SDK would print.

Also, I see that you are using length as milliseconds. We expect length to be in seconds, here's the API doc [reference](https://adobe-marketing-cloud.github.io/video-heartbeat-v2/reference/ios/Classes/ADBMediaHeartbeat.html#//api/name/createMediaObjectWithName:mediaId:length:streamType:).
