### ISSUE TITLE
Error on Pod install for tvOS

### ISSUE THREAD

**Issue by daisyramos317** [Adobe-Marketing-Cloud/video-heartbeat-v2#31]
Steps to reproduce:

Podfile tvOS target:

```
target 'NBC-Player-TVOS' do
  platform :tvos, '10.0'
  pod 'AdobeVideoHeartbeatSDK', '2.1.0'

end
```

Error on pod install:

*[!] The platform of the target `NBC-Player-TVOS` (tvOS 10.0) is not compatible with `AdobeVideoHeartbeatSDK (2.1)`, which does not support `tvos`*

**Comment by addb** [comment]
@daisyramos317 

We handle TvOS as a subspec. Please try adding the pod as follows
pod 'AdobeVideoHeartbeatSDK/TVOS', '2.1.0'

Thanks,
Arjun

**Comment by daisyramos317** [comment]
perfect, thanks. Will close this

**Comment by addb** [comment]
@daisyramos317 

For Swift Player you will have to create a bridging header file which is nothing but a .h file

and insert these import statements:

#import "ADBMediaHeartbeat.h"
#import "ADBMediaHeartbeatConfig.h"
#import "ADBStandardMetadataKeys.h"

and then insert the path to yourBridgingHeaderFile.h as a value for the field `Objective-C Bridging Header` under the build settings.

Then you can start using MediaHeartbeat classes without importing anywhere else. 

Thanks,
Arjun

**Comment by daisyramos317** [comment]
Ah thought that might be the case when I saw the static lib in the pods, we can't use a bridging header in this case since it's a framework target. I'll create a module map and come back with an update. Thanks

**Comment by daisyramos317** [comment]
@addb the module map worked fine, any chance you will distribute this library as a dynamic cocoapod in the future?

**Comment by addb** [comment]
@daisyramos317 As of now we don't have any plans to do that.
