### ISSUE TITLE
podPosition

### ISSUE THREAD

**Issue by efrainaperador** [Adobe-Marketing-Cloud/video-heartbeat-v2#33]
Hi I'm having an issue when I send position 0 for the adStart event, I'm creating an object using CreateAdObject but when I send the information to the server I'm getting podPosition=0.0 instead of only podPosition=0

`this.heartbeat.trackEvent(this.MediaHeartbeat.Event.AdStart, adObject);`

**Comment by praveek** [comment]
@efrainaperador  Which platform and version are you seeing this issue in ?

**Comment by efrainaperador** [comment]
@praveek We are using javascript version 2.1.0

**Comment by praveek** [comment]
We have identified the issue. We will shortly update our javascript library with fix for this issue.

**Comment by praveek** [comment]
@efrainaperador This has been fixed in 2.1.1 version of our JS library (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/releases/tag/js-v2.1.1)
