### ISSUE TITLE
Track Event for Ads not working

### ISSUE THREAD

**Issue by sathishkraj** [Adobe-Marketing-Cloud/video-heartbeat-v2#4]
Track event for .adBreakStart, .adStart, .adComplete and .adBreakComplete is not working for me. I followed the documentation and sample app, not sure what I am missing. In 1x version, I had to give a delay after onComplete event before releasing the plugin to  avoid track event abort. Is there any similar workaround for this?

**Comment by praveek** [comment]
@sathishkraj Which platform are you seeing this issue in ? Do you pass in valid AdBreakInfo and AdInfo objects to the corresponding calls ?

**Comment by sathishkraj** [comment]
@praveek Seeing this issue in iOS, I do pass AdBreakInfo and AdInfo using this class method createAdBreakObject and createAdObject. Is there a way check its validity?. Let me know if you need more info.

**Comment by praveek** [comment]
The correct order of video tracking APIs for a pre-roll scenario is the following

1) .trackSessionStart
2) .adBreakStart
3) .adStart
4) .trackPlay (for the first ad playback of the pre-roll adBreak only)
4) .adComplete
5) .adBreakComplete
6) .chapterStart
7) .trackPlay (optional, content playback automatically after AdBreak).

**Comment by sathishkraj** [comment]
@praveek thanks, let me try this
