### ISSUE TITLE
Dead -lock in VideoHeartbeat library

### ISSUE THREAD

**Issue by hamadycisse** [Adobe-Marketing-Cloud/video-heartbeat-v2#5]
A dead lock may occur in the Heartbeat library.

Decompiling the code led me to the  class Channel to be the cause
`public void trigger(Event event) {
      synchronized(this) {
            if(!this._isShutDown) {
                Iterator var3 = this._listeners.entrySet().iterator();

                while(true) {
                    String eventType;
                    List handlers;
                    do {
                        if(!var3.hasNext()) {
                            return;
                        }

                        Entry entry = (Entry)var3.next();
                        eventType = (String)entry.getKey();
                        handlers = (List)entry.getValue();
                    } while(!_matchWildcard(eventType, event.getName()));

                    Iterator var7 = handlers.iterator();

                    while(var7.hasNext()) {
                        Channel.EventHandler handler = (Channel.EventHandler)var7.next();
                        **handler.getCallback().call(event);**
                    }
                }
            }
        }
    }`

The following threads could dead lock each other; **VideoHeartbeatClock** and the thread used to make the Network calls. (spawned on the thread pool). The deadlock can be cause if callback of one of the handlers also trigger and event using the same data channel used be another callback to trigger another event at the same time.

Here is the dump of the stack trace of the threads spawned by the library and which are impacted by the issue

•	"<35> VideoHeartbeatClock"@830,040,864,480 in group "main": MONITOR
	•	**INSTANCE B - trigger:157, Channel {com.adobe.primetime.core.radio} ——— LOCKED**
	•	call:185, Timer$3 {com.adobe.primetime.va.plugins.ah.engine.clock}
	•	**INSTANCE A - trigger:167, Channel {com.adobe.primetime.core.radio}**
	•	trigger:176, PluginManager {com.adobe.primetime.core.plugin}
	•	_trigger:201, BasePlugin {com.adobe.primetime.core.plugin}
	•	onTick:132, ClockService {com.adobe.primetime.va.service.clock}
	•	_onTick:203, TimerManager {com.adobe.primetime.va.service.clock}
	•	access$300:30, TimerManager {com.adobe.primetime.va.service.clock}
	•	run:83, TimerManager$Timer$1 {com.adobe.primetime.va.service.clock}
	•	handleCallback:733, Handler {android.os}
	•	dispatchMessage:95, Handler {android.os}
	•	loop:146, Looper {android.os}
	•	run:61, HandlerThread {android.os}
	•	
	•	
	•	
	•	"<57> pool-40-thread-1"@830,042,159,192 in group "main": MONITOR
	•	**#INSTANCE A - trigger:157, Channel {com.adobe.primetime.core.radio}  ——— LOCKED**
	•	trigger:176, PluginManager {com.adobe.primetime.core.plugin}
	•	_trigger:201, BasePlugin {com.adobe.primetime.core.plugin}
	•	access$3400:42, AdobeHeartbeatPlugin {com.adobe.primetime.va.plugins.ah}
	•	call:626, AdobeHeartbeatPlugin$22 {com.adobe.primetime.va.plugins.ah}
	•	**INSTANCE B - trigger:167, Channel {com.adobe.primetime.core.radio}**
	•	call:238, Network$3$1 {com.adobe.primetime.va.plugins.ah.engine.network}
	•	trigger:167, Channel {com.adobe.primetime.core.radio}
	•	run:161, URLLoader$1 {com.adobe.primetime.core}
	•	runWorker:1112, ThreadPoolExecutor {java.util.concurrent}
	•	run:587, ThreadPoolExecutor$Worker {java.util.concurrent}
	•	run:841, Thread {java.lang}
	•	"<58> pool-42-thread-1"@830,040,542,632 in group "main": WAIT
	•	wait:-1, Object {java.lang}
	•	parkFor:1205, Thread {java.lang}
	•	park:325, Unsafe {sun.misc}
	•	park:157, LockSupport {java.util.concurrent.locks}
	•	await:2017, AbstractQueuedSynchronizer$ConditionObject {java.util.concurrent.locks}
	•	take:410, LinkedBlockingQueue {java.util.concurrent}
	•	getTask:1035, ThreadPoolExecutor {java.util.concurrent}
	•	runWorker:1097, ThreadPoolExecutor {java.util.concurrent}
	•	run:587, ThreadPoolExecutor$Worker {java.util.concurrent}
	•	run:841, Thread {java.lang}
	•	
	•	
	•	
	•	"<59> pool-39-thread-1"@830,041,668,096 in group "main": MONITOR
	•	**request:217, Channel {com.adobe.primetime.core.radio}  ——— LOCKED**
	•	request:213, Channel {com.adobe.primetime.core.radio}
	•	call:198, ReportFilter$2 {com.adobe.primetime.va.plugins.ah.engine.filter}
	•	run:40, Command {com.adobe.primetime.core.radio}
	•	call:422, Executors$RunnableAdapter {java.util.concurrent}
	•	run:237, FutureTask {java.util.concurrent}
	•	runWorker:1112, ThreadPoolExecutor {java.util.concurrent}
	•	run:587, ThreadPoolExecutor$Worker {java.util.concurrent}
	•	run:841, Thread {java.lang}

**Comment by praveek** [comment]
@hamadycisse Thanks for the detailed information. We will look into this issue.

**Comment by hamadycisse** [comment]
Any updates on this issue? It' blocking us from releasing our latest version with Heartbeat.

Thank you

**Comment by praveek** [comment]
We have a fix for this issue and are planning for an official release. Meanwhile can you contact us through your Adobe Representative to get an early access to the build. 

Thanks.

**Comment by hamadycisse** [comment]
Awesome, thanks!! I LL test it asap
