### ISSUE TITLE
Publish to CocoaPods!

### ISSUE THREAD

**Issue by f2prateek** [Adobe-Marketing-Cloud/video-heartbeat-v2#7]
Hi!

I noticed you just added a cocoa pods branch (https://github.com/Adobe-Marketing-Cloud/video-heartbeat-v2/tree/cocoapod). We were actually just trying to setup something similar ourselves to use the library via CocoaPods - but it' be much better if you could use the official version. Any idea when it would be released? We'd be happy to test out a beta version from CocoaPods too!

**Comment by himanshuphalak** [comment]
Hi @f2prateek, AdobeVideoHeartbeatSDK pod is now available on CocoaPods for usage [here](https://cocoapods.org/pods/AdobeVideoHeartbeatSDK).

**Comment by f2prateek** [comment]
Thanks! We just started using it.
