### ISSUE TITLE
Capture App version with JS SDK

### ISSUE THREAD

**Issue by nishantkp** [Adobe-Marketing-Cloud/video-heartbeat-v2#76]
Hi,

I have a React application and wanted to capture React App version through the heartbeat SDK. I am setting the App version like below,
 
```javascrpt
// Create MediaConfig object (same as above)
var mediaConfig = new ADB.MediaConfig();
mediaConfig.trackingServer = Configuration.MEDIA_COLLECTION_ENDPOINT;
mediaConfig.playerName = Configuration.PLAYER_NAME;
mediaConfig.channel = Configuration.CHANNEL;
mediaConfig.appVersion = Configuration.APP_VERSION;
mediaConfig.debugLogging = false;
mediaConfig.ssl = true;

ADB.Media.configure(mediaConfig, appMeasurement);
```

mentioned [here](https://experienceleague.adobe.com/docs/media-analytics/using/sdk-implement/setup/setup-javascript/set-up-js-3.html?lang=en).

Is this the correct way to capture App version?
Because my report suite is not getting populated with the App version?

**Comment by emdobrin** [comment]
Hi @nishantkp, can you also share the network request from your app for sessionStart?

**Comment by cacheung** [comment]
You can also take a look of the [JS 3.x sample app](https://github.com/Adobe-Marketing-Cloud/media-sdks/tree/master/sdks/js/3.x/samples/MediaAnalyticsSample).
In the sample app, it sets[ appVersion](https://github.com/Adobe-Marketing-Cloud/media-sdks/blob/master/sdks/js/3.x/samples/MediaAnalyticsSample/script/app/analytics/video.analytics.provider.js#L54) to use the sdk version set in the  [Configuration.js](https://github.com/Adobe-Marketing-Cloud/media-sdks/blob/master/sdks/js/3.x/samples/MediaAnalyticsSample/script/app/configuration.js#L39).

Do you set your React APP Version for Configuration.APP_VERSION?

**Comment by nishantkp** [comment]
Hi @emdobrin, 

here is the session start call.

<img width="1197" alt="Screen Shot 2022-05-12 at 1 32 46 PM" src="https://user-images.githubusercontent.com/32653955/168135019-7ac89853-b320-4700-b00a-63b87de28f19.png">

@cacheung yes I am setting the application version (not react library version, it is just the app version) as `mediaConfig.appVersion`.

**Comment by nishantkp** [comment]
yes, `1.1.0` is the version I set with `mediaConfig.appVersion = Configuration.APP_VERSION;`

**Comment by cacheung** [comment]
You can create custom processing rule for the value to show up in reporting.

**Comment by addb** [comment]
@nishantkp app version is sent as `media.libraryVersion` param.
![Uploading Screen Shot 2022-05-12 at 2.57.44 PM.png…]()
