### ISSUE TITLE
API call trackPlay is unsupported in the current state.

### ISSUE THREAD

**Issue by CoderXpert** [Adobe-Marketing-Cloud/video-heartbeat-v2#9]
I am integrating Adobe heartbeat sdk to track video analytics, tracking methods (trackPlay, trackPause etc) are not working, 👇  are the message get printed on console.

```
[DEBUG][ADBMediaHeartbeat] ::trackPlay
[WARN] [ADBMediaHeartbeat] API call trackPlay is unsupported in the current state.
```

`ADBMediaHeartbeat(delegate: heartbeatDataProvider, config: config)` 👈 the way we create instance. 

*Note: * I am sending analytics data to same instance as Analytics Adobe instance.

**Comment by himanshuphalak** [comment]
@CoderXpert, Are you beginning the video tracking session by calling trackSessionStart API? Please refer to this documentation [here](https://marketing.adobe.com/resources/help/en_US/sc/appmeasurement/hbvideo/c_vhl_track-core-vid-playback.html) if you need further details around this.

Also, can you elaborate more on sending analytics data to same instance as Analytics Adobe instance?

**Comment by CoderXpert** [comment]
@himanshuphalak thanks for sharing the doc and seems like this was the issue. However I still can't see requests being made on charles. 
With standard adboe sdk I can see network requests when we track something, howeve not with heartbeat sdk.

**Comment by himanshuphalak** [comment]
@CoderXpert Sorry to hear that you are still unable to see any network traffic. At this point, we would need additional details about implementation to look into this further. Can you please reach out to [client care](http://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket with them. We can assist you better through this route and make sure you have everything you need. 
For any other questions, feel free to post an update. I'd be happy to answer them.

**Comment by CoderXpert** [comment]
Thanks for your help, I will create a ticket with client care.
